### ISSUE TITLE
cue_file overwrite existing tag

### ISSUE THREAD

**Issue by LordHelmchen666** [Moonbase59/autocue#12]
In AzuraCast I have enabled write tags. Now I noticed on one file that already manually set tag is overwritten each time on playout.
It is a one second silent track that triggers ad injection for laut.fm
I write tags liq_amplify and replaygain_track_gain to 0.00dB manually. But every time cue_file override both with 52.0dB.
Is it correct behavior? I thought cue_file will not touch existing tags.
I will provide more info later, I am writing from my mobile. :)

**Comment by Moonbase59** [comment]
I fear this is intended behaviour. In general, I recommend _not_ using write_tags/write_replaygain, because it can but unduly strain on the disks. It _does_ write tags on every playout (since settings might have changed), which can lead to having to write the whole file again.

Pre-tagging—if possible—is a much more resource-friendly way to do it. If relevant settings are changed, `cue_file` will still initiate a re-analysis if necessary (but tries to avoid that).

If you have pre-tagged that special file _once_, and then manually corrected certain values, you can add a tag `liq_cue_file=false` to it, which should prevent Autocue from ever touching it again. I made that "switch" exactly for such cases.

The pre-tagging is needed, because if Autocue doesn’t touch it, it will otherwise have no cueing, fading and gain data.

Let me know if this works out for you!

**Comment by Moonbase59** [comment]
Just did a quick test, and it worked fine here:

```
2024/06/09 15:35:26 [autocue.cue_file:2] Skipping cue_file for "/home/matthias/media/videostream/yyy/Beatles, The - Strawberry Fields Forever.flac" because liq_cue_file=false forbids it.
2024/06/09 15:35:26 [autocue.metadata:2] No autocue data found for file /home/matthias/media/videostream/yyy/Beatles, The - Strawberry Fields Forever.flac
```

```
2024/06/09 15:35:56 [show_meta:3] ("liq_amplify", "-1.33 dB")
2024/06/09 15:35:56 [show_meta:3] ("liq_amplify_adjustment", "0.00 dB")
2024/06/09 15:35:56 [show_meta:3] ("liq_blank_skipped", "true")
2024/06/09 15:35:56 [show_meta:3] ("liq_blankskip", "true")
2024/06/09 15:35:56 [show_meta:3] ("liq_cross_start_next", "44.")
2024/06/09 15:35:56 [show_meta:3] ("liq_cue_duration", "211.50")
2024/06/09 15:35:56 [show_meta:3] ("liq_cue_file", "false")
2024/06/09 15:35:56 [show_meta:3] ("liq_cue_in", "30.")
2024/06/09 15:35:56 [show_meta:3] ("liq_cue_out", "45.")
2024/06/09 15:35:56 [show_meta:3] ("liq_dummy", "DUMMY")
2024/06/09 15:35:56 [show_meta:3] ("liq_fade_in", "1.")
2024/06/09 15:35:56 [show_meta:3] ("liq_fade_out", "2.5")
2024/06/09 15:35:56 [show_meta:3] ("liq_longtail", "false")
2024/06/09 15:35:56 [show_meta:3] ("liq_loudness", "-16.67 LUFS")
2024/06/09 15:35:56 [show_meta:3] ("liq_loudness_range", "9.62 LU")
2024/06/09 15:35:56 [show_meta:3] ("liq_reference_loudness", "-18.00 LUFS")
2024/06/09 15:35:56 [show_meta:3] ("liq_true_peak", "0.930000")
2024/06/09 15:35:56 [show_meta:3] ("liq_true_peak_db", "-0.63 dBFS")
2024/06/09 15:35:56 [show_meta:3] ("replaygain_reference_loudness", "-18.00 LUFS")
2024/06/09 15:35:56 [show_meta:3] ("replaygain_track_gain", "-1.34 dB")
2024/06/09 15:35:56 [show_meta:3] ("replaygain_track_peak", "0.930153")
2024/06/09 15:35:56 [show_meta:3] ("replaygain_track_range", "9.10 dB")
2024/06/09 15:35:56 [show_meta:3] Now playing: The Beatles - Strawberry Fields Forever
2024/06/09 15:35:56 [show_meta:2] Blank (silence) detected in track, ending early.
```

**Comment by LordHelmchen666** [comment]
Thanks for this good explanation. Is there any easy way to run `cue_file` on many folders/files? bash, python or something else. Or maybe something like rgbpm2 for loudgain? 
 
Now I use this settings:
```# settings.autocue.cue_file.path := "cue_file"
 settings.autocue.cue_file.fade_in := 0.5  # seconds
 settings.autocue.cue_file.fade_out := 5.0  # seconds
# settings.autocue.cue_file.timeout := 60.0  # seconds
# settings.autocue.cue_file.target := -18.0  # LUFS
# settings.autocue.cue_file.silence := -42.0  # LU below track loudness
# settings.autocue.cue_file.overlay := -8.0  # LU below track loudness
# settings.autocue.cue_file.longtail := 15.0  # seconds
# settings.autocue.cue_file.overlay_longtail := -15.0  # extra LU
 settings.autocue.cue_file.noclip := true  # clipping prevention like loudgain's `-k`
# settings.autocue.cue_file.blankskip := false  # skip silence in tracks
# settings.autocue.cue_file.unify_loudness_correction := true  # unify `replaygain_track_gain` & `liq_amplify`
# settings.autocue.cue_file.write_tags := true  # write liq_* tags back to file
# settings.autocue.cue_file.write_replaygain := true  # write ReplayGain tags back to file
# settings.autocue.cue_file.force_analysis := false  # force re-analysis even if tags found
# settings.autocue.cue_file.nice := false  # Linux/MacOS only: Use NI=18 for analysis

**Comment by Moonbase59** [comment]
Since I never came round to writing a "wrapper" (yet!), I actually thought about hacking it into my `rgbpm`…

You could also "steal" the folder traversal code from, say, [`rmlyrics3`](https://github.com/Moonbase59/rmlyrics3) (in `main`), it’s just Python.
