### ISSUE TITLE
Song skiped when it has a less than 1 sec silence gap and skipblank is enabled

### ISSUE THREAD

**Issue by shamu450** [Moonbase59/autocue#9]
Hello! Not much of an issue, maybe more of a setting request. Wondering if a setting to set the minimum length that silence needs to be in order for the song to be skipped can be implemented to use along side the blankskip setting.

Why? Well, I have some songs that have small silences that seem to be getting skipped when I have blankskip enabled. 

A song that has a small (less than one second) silence near the 1 minute and 5 second mark and with skipblank enabled once it gets detected the song gets skipped. short silence near beg. of track; image - https://imgur.com/a/3HAbo9D top image

Another song I have that has a short silence near end of track; image - https://imgur.com/a/3HAbo9D bottom image,  gets skipped as well when blankskip is enabled.
```
2024/06/06 08:37:24 [next_song:3] Prepared "/var/azuracast/stations/nobullishradio/media/Makaveli/Reparation Is Due (2006)/Makaveli - Reparation Is Due - 13 - Dirty Game.flac" (RID 560).
2024/06/06 08:37:24 [show_meta:3] Now playing: Gritty Outlaw - Dirty Game
2024/06/06 08:37:24 [show_meta:2] Blank (silence) detected in track, ending early.
2024/06/06 08:37:24 [cross:3] Analysis: -60.513169dB / -14.637370dB (0.38s / 0.38s)
2024/06/06 08:37:24 [cross:3] Computing crossfade transition over reconciled duration with 0.38s ending and 0.38s starting buffered data.
```

Thank you!

**Comment by Moonbase59** [comment]
You can read my mind! This is actually on my internal roadmap since a while, but I wanted to be sure that everything works stable before.

Rest assured it will come ;-)

**Comment by shamu450** [comment]
> You can read my mind! This is actually on my internal roadmap since a while, but I wanted to be sure that everything works stable before.
> 
> Rest assured it will come ;-)

Amazing!

**Comment by Moonbase59** [comment]
My plan is to have a settable parameter that lets you specify the _minimum silence length_ on which it operates, and if it did find a silent part of specified length, it would cue out at the beginning of said silent part.

Would that fit your use case?

**Comment by shamu450** [comment]
> @shamu450 My plan is to have a settable parameter that lets you specify the _minimum silence length_ on which it operates, and if it did find a silent part of specified length, it would cue out at the beginning of said silent part.
> 
> Would that fit your use case?

That sounds great, it would allow me to set it to say .. 4s and anything with a silence longer than 4s would be skipped and faded to the next track. Allows me to keep songs with short gaps and skip the songs that have hidden tracks that start much later. That seems to work great for me.

Thank you very much!

**Comment by LordHelmchen666** [comment]
> That sounds great, it would allow me to set it to say .. 4s and anything with a silence longer than 4s would be skipped and faded to the next track. Allows me to keep songs with short gaps and skip the long silence in songs that have hidden tracks that start much later. That seems to work great for me.
> 
> Thank you very much!

That's exactly what I wanted to ask. I would need the same thing.

**Comment by Moonbase59** [comment]
@shamu450 @LordHelmchen666 **It’s here!** [Version 3.0.0](https://github.com/Moonbase59/autocue/releases) features **adjustable minimum silence length** for blank skipping!

Check out the Release Notes. Happy autocueing!
